### ISSUE TITLE
The Suggest feature inserts doublequotes around seeded text

### ISSUE THREAD

**Issue by eternaldensity** [croxis/mtgai#5]
example:

```
        [0mcreating an LSTM...[0m 
[0mseeding with "|binder mindstone||enchantment||"[0m 
[0m--------------------------[0m  
"|binder mindstone||enchantment||"N||{^^^UU}|players have no cards from all graveyards.|
```

**Comment by croxis** [comment]
Fixed

**Comment by eternaldensity** [comment]
It's still happening on the site.  Is this fix not live yet?

**Comment by croxis** [comment]
Not yey. I'm lso getting scrambled text with an update to the neural
network. I'm out camping (currently hiding in the cafe of a cheesefactory)
but I'll start working opn it when I get home monday next week.

On Sun, Aug 9, 2015 at 8:49 PM, eternaldensity notifications@github.com
wrote:

> It's still happening on the site. Is this fix not live yet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/croxis/mtgai/issues/5#issuecomment-129289736.

## 
- David - Proud to be saving the world since 1984

**Comment by eternaldensity** [comment]
Ah, no worries, just making sure it wasn't meant to be fixed currently.
Enjoy your camping! :D
